/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import javax.swing.WindowConstants;

/**
 *
 * @author mildr
 */
public class ModificarComp extends javax.swing.JFrame {

    /**
     * Creates new form ModificarComp
     */
    public ModificarComp() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setTitle("Modificar Computadora");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_labId = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmb_comId = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        labEst = new javax.swing.JLabel();
        cmb_estado = new javax.swing.JComboBox<>();
        do_modLab = new javax.swing.JCheckBox();
        cmb_newLabId = new javax.swing.JComboBox<>();
        btn_mod = new javax.swing.JButton();
        do_obs = new javax.swing.JCheckBox();
        obs = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Modificar Computadoras");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Laboratorio ID");

        cmb_labId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_labId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmb_labId.setEnabled(false);
        cmb_labId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_labIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Eligir Computadora");

        cmb_comId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_comId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmb_comId.setEnabled(false);
        cmb_comId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_comIdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Información de Computadora");

        labEst.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labEst.setText("Estado");
        labEst.setEnabled(false);

        cmb_estado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_estado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmb_estado.setEnabled(false);
        cmb_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_estadoActionPerformed(evt);
            }
        });

        do_modLab.setText("Mover de Laboratorio");
        do_modLab.setEnabled(false);
        do_modLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                do_modLabActionPerformed(evt);
            }
        });

        cmb_newLabId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_newLabId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmb_newLabId.setEnabled(false);
        cmb_newLabId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_newLabIdActionPerformed(evt);
            }
        });

        btn_mod.setText("Actualizar Computadora");
        btn_mod.setEnabled(false);
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        do_obs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        do_obs.setText("Observaciones");
        do_obs.setEnabled(false);

        obs.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btn_mod))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(do_obs)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(do_modLab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb_newLabId, 0, 114, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labEst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_comId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_labId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(obs))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_labId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_comId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEst)
                    .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(do_modLab)
                    .addComponent(cmb_newLabId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(do_obs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obs, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_mod)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_newLabIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_newLabIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_newLabIdActionPerformed

    private void cmb_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_estadoActionPerformed

    private void cmb_comIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_comIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_comIdActionPerformed

    private void do_modLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_do_modLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_do_modLabActionPerformed

    private void cmb_labIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_labIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_labIdActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_mod;
    public javax.swing.JComboBox<String> cmb_comId;
    public javax.swing.JComboBox<String> cmb_estado;
    public javax.swing.JComboBox<String> cmb_labId;
    public javax.swing.JComboBox<String> cmb_newLabId;
    public javax.swing.JCheckBox do_modLab;
    public javax.swing.JCheckBox do_obs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel labEst;
    public javax.swing.JTextField obs;
    // End of variables declaration//GEN-END:variables
}
